spring:
  application:
    name: banking-app





server:
  port: 8080

razorpay:
  key-id: ...
  secret: ...

fraud:
  url: ...

loan:
  url: ...
frontend:
  url: ...
security:
  jwt:
    secret: ...
    issuer: ...
    access-token-minutes: ...
    refresh-token-days: ...
